name: SpacePlugin
main: io.github.LilParker.SpacePlugin.SpacePlugin
version: 0.001

commands:
  genempty:
    description: Generates a world without any blocks (For making space station/space ship maps).
    usage: /genempty (name)
    
  genhill:
    description: Generates a world with hopefully some hills
    usage: /genhill (name)
    
  genoverhang:
    description: Generates a world with overhangs
    usage: /genoverhang (name)
  
  tpd:
    description: Changes your world
    usage: /tpd (world name)
  
  unload:
    description: Unloads a world ***WARNING SORT OF BROKEN***
    usage: /unload (world name)
    
  load:
    description: Loads a world
    
  bbf:
    description: Block beneath feet. That's all.
    usage: /bbf